### ISSUE TITLE
NO compile Yaml error

### ISSUE THREAD

**Issue by TTHOMAS52** [eni23/micronova-controller#10]
Hello I use Ubuntu22.04, with plateformio and python3.10.12
when I compile  I have this message 
-- Preferences @ 2.0.0
Building in release mode
ModuleNotFoundError: No module named 'yaml':
  File "/home/titi/.platformio/penv/lib/python3.10/site-packages/platformio/builder/main.py", line 180:
    env.SConscript(env.GetExtraScripts("post"), exports="env")
  File "/home/titi/.platformio/packages/tool-scons/scons-local-4.6.0/SCons/Script/SConscript.py", line 609:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/titi/.platformio/packages/tool-scons/scons-local-4.6.0/SCons/Script/SConscript.py", line 279:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/titi/Téléchargements/micronova-controller-master/tools/yaml-config.py", line 3:
    import yaml

Can you help me please

**Comment by eni23** [comment]
You need the python package `PyYAML` in order to compile. I guess on ubuntu its something like:
```
sudo apt install python-yaml
```

**Comment by TTHOMAS52** [comment]
thank

**Comment by TTHOMAS52** [comment]
now the web page still on "please wait"

**Comment by TTHOMAS52** [comment]
I can read in putty all value.

**Comment by eni23** [comment]
@TTHOMAS52 

In order to help you debug your issues, i would ask you for more detailed informations about your enviroment:

- How does your hardware looks, what is your stove, how does the circuit looks?
- Where do you see "please wait". If its on the web, what are the console logs (devtools, F12), what are the requests, how is your network configured, etc etc
- Do you have any other logs?
- Anything else?

Please note that while i try to help everyone interested, this is a personal project and i can only give super limited end-user support.

**Comment by TTHOMAS52** [comment]
Hello thanks for helping,
--> My stove is a extraflame divina plus, the board is a micronova. and the "adaptaro with the 3 optocoupler is ok".
--> The pinout of the stove's serial  is not exactly the same. (gnd, serial, 20V,5V) 
--> I know that the code are not the same,( I made my self plugins for espeasy but have a probleme if you are intereste I can send it).
--> I used putty (serial 8n2..) and read the " temperature".
I don't use devtools or, F12, sometime I use the monitor in arduino ide
For the network ,I only configure SSID and PASSWORD,
![Capture d’écran du 2024-02-22 18-36-42](https://github.com/eni23/micronova-controller/assets/20043639/f3101b1d-45fb-4326-8d55-a981416ea67c)

**Comment by TTHOMAS52** [comment]
I will configure this var in index.html
![Capture d’écran du 2024-02-22 18-51-55](https://github.com/eni23/micronova-controller/assets/20043639/2d591e67-3f92-4e8b-b186-113029cbf386)

**Comment by TTHOMAS52** [comment]
Hello on the consol log (F12) there is no request. I use an esp32 wroom. I make some research, about semaphore,

**Comment by TTHOMAS52** [comment]
probleme solve, I install html-minifier

**Comment by eni23** [comment]
@TTHOMAS52: Perfect, can we close the issue now?
