### ISSUE TITLE
3 littles bugs

### ISSUE THREAD

**Issue by TTHOMAS52** [eni23/micronova-controller#12]
Hello there is 3 bugs in web_server.cpp

line 110 and 142: You must change with that

  String value = request->getParam("value", true)->value();
and line 151 replace with :             stove.write_eeprom(addr_s, value_s);

**Comment by eni23** [comment]
Hey

Your ticket description is vague, does not tells what problem occurs, thus i cannot understand what is not working.

**Comment by TTHOMAS52** [comment]
`// write-ram
    // POST only supports one param
    web_server->on("/api/ram", HTTP_POST, [](AsyncWebServerRequest *request){
        if (request->hasParam("addr", true) && request->hasParam("value", true)) {
            String answer = "OK";
            String addr = request->getParam("addr", true)->value();
            String value = request->getParam("addr", true)->value();
            uint8_t addr_s = hexstr2uint(addr);
            uint8_t value_s = hexstr2uint(value);
            if( !xSemaphoreTake( xStoveSemaphore, ( TickType_t ) STOVE_SEMAPHORE_WAIT_TICKS ) == pdTRUE ){
                request->send(500, "text/plain", "err_lock");
                return;
            }`

**Comment by TTHOMAS52** [comment]
For the 2  first error, 
when you want to write in ram or eeprom, you don't use the "value" to write in ram or in eeprom, but the "adress" value.
for exemple if you want to write in ram the value 0x32 at the adress 0x57, the parametre of the function are
  "stove.write_ram(0x57, 0x57);" and not   "stove.write_ram(0x57, 0x32);" 

for the last, if you want to write in **eeprom**, you use the function  "stove.write_ram" 
so you write a new value in the **ram**, but it must be  "stove.write_eeprom".

**Comment by TTHOMAS52** [comment]
![image](https://github.com/eni23/micronova-controller/assets/20043639/d12435aa-ec0a-4d3a-90c4-c8590af246b6)

**Comment by TTHOMAS52** [comment]
![image](https://github.com/eni23/micronova-controller/assets/20043639/04dd270c-ee67-474c-a417-107b08a4c804)

**Comment by eni23** [comment]
@TTHOMAS52 indeed (i never really used the HTTP API thb). Fixed with the latest commit.
