### ISSUE TITLE
Migrate project for ESP8266

### ISSUE THREAD

**Issue by ciao87** [eni23/micronova-controller#7]
Hello, how could I convert the project for ESP8266? In the src folder I don't see the file web_content.h.

**Comment by eni23** [comment]
I doubt this project will be able to run on a ESP8266, not sure if the performance will be enough, and AFAIK the console library is not available for ESP32. Its probably easier and way cheaper to just buy a 5$ ESP32 board. 

But to answer your question: The file `web_content.h` is dynamically created with the script `tools/build-web.py` (just run `make` or `make upload`) when building it with Platformio, which is a hard dependency to build it.

**Comment by ciao87** [comment]
Thanks.
